version: '3'
services:
  web:
    container_name: facturacion
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/facturacion
    ports:
      - "3000:3000"
    expose:
      - '3000'